### ISSUE TITLE
how to create few routes/pages?

### ISSUE THREAD

**Issue by Hazantip** [micooz/es6-webpack2-starter#106]
There is index.html file, but if i want to have more pages like -  /about, /products, etc..
how i can add new pages?
![screen shot 2017-07-10 at 11 15 41](https://user-images.githubusercontent.com/6676603/28008664-29788c7c-6561-11e7-9ffa-58411f680eb4.png)
At this moment i did it this way, but if there is will be 20 pages??

**Comment by micooz** [comment]
This starter aims to create a **Single Page Application** aka SPA, so it's not recommend to create more than one **.html** files, one html is enough.

However, for multiple pages(your purpose) you can simply duplicate **HtmlWebpackPlugin** using **map**:

```js
const htmls = ['index.html', 'about.html', ...more htmls];

plugins: [
  ...htmls.map((html) => new HtmlWebpackPlugin({
    inject: true,
    template: path.resolve(__dirname, `../static/${html}`),
    favicon: path.resolve(__dirname, '../static/favicon.ico')
  })),
  // other plugins 
]
```

**Comment by Hazantip** [comment]
@micooz, thanks!
So, how you recommend to manage routes/view with your boilerplate?

**Comment by micooz** [comment]
It's not a problem if you integrate framework such as react(react-router), vue(vue-router) etc..

For projects not using huge frameworks, you can choose a tiny URL router. I recommend to use [director](https://github.com/flatiron/director) for this purpose.

**Comment by Hazantip** [comment]
Thank you for your boilerplate! :) 👍
