### ISSUE TITLE
images processing

### ISSUE THREAD

**Issue by Hazantip** [micooz/es6-webpack2-starter#107]
![screen shot 2017-07-10 at 11 17 31](https://user-images.githubusercontent.com/6676603/28008739-6d26a7d8-6561-11e7-9287-09be44ad24b2.png)

As you see, each image that i want to use i should require, but how to work with images with more comfortable way(without need to require each one)?

**Comment by micooz** [comment]
With 30a21abda9ec0aee2d99d7174fc49c11327394b7 you can put your images to `static/path/to/your/*.png`, then access them directly from **src** without **require**:

```js
<img src="/path/to/your/about.png" alt=""/>
```

**Comment by Hazantip** [comment]
Thanks! 👍

**Comment by Hazantip** [comment]
There is a one thing that doesn't work:

`background: url('/assets/images/discretion.png') center center / cover no-repeat;`
`<img src="/assets/images/dunk.jpg" alt="">`

this works good for development, but doesn't for build;
build requires to have source like:
`<img src="assets/images/dunk.jpg" alt="">` - without '/' at the beginning

**Comment by micooz** [comment]
How did you serve `dist` in production?

It should be worked if you serve them on a server not `file://` I guess.

----

For example:

```
$ npm i -g http-server
$ http-server dist/
```

Then open `http://localhost:8080`.

**Comment by Hazantip** [comment]
You're right. On a server it works fine, but locally(file://) isn't possible?

**Comment by micooz** [comment]
Generally speaking, **file://** is rarely used in practice. You should always running a server rather than double-click `index.html`.
