### ISSUE TITLE
Missing lint config?

### ISSUE THREAD

**Issue by ifuller1** [micooz/es6-webpack2-starter#111]
Is the ESLint config missing? I did a fresh install after cloning and `npm run start` failed because there was no lint config. Does this seem right?

Thanks!

**Comment by micooz** [comment]
How did you "clone"? There is a hidden file named **.eslintrc.js**. Try list **all** files in your project folder and see if it exist.

**Comment by ifuller1** [comment]
I'm so sorry. I totally forgot that I'd moved the folder.
