### ISSUE TITLE
Could you explain the Proxy stuff

### ISSUE THREAD

**Issue by chopfitzroy** [micooz/es6-webpack2-starter#88]
I am a little unclear on what the proxy stuff is for and why it is referencing github and npm a clarification would be great :).

Cheers.

**Comment by micooz** [comment]
This is a good question!

For front-end projects, it's important to fetch resource from servers in **development**. Sometimes the server is not `localhost`. So we need Cross-origin resource sharing (CORS). 

Proxy is the best practice to do CORS. You can develop your projects anywhere without a huge  server running at back-end.

`github` and `npm` are just two examples in this project.

**Comment by chopfitzroy** [comment]
Ahh that makes sense :) thank you.
