### ISSUE TITLE
proxies

### ISSUE THREAD

**Issue by s3c0nDD** [micooz/es6-webpack2-starter#99]
what are proxies?

**Comment by micooz** [comment]
Proxy allows you to fetch data from localhost or different domains. That is to say, It solves the problem of cross-domain request in **development**. Proxy is the best practice.

See:

https://github.com/micooz/es6-webpack2-starter/blob/master/proxy/rules.js#L2
https://github.com/micooz/es6-webpack2-starter/blob/master/src/bootstrap.js#L25

**Comment by s3c0nDD** [comment]
Thansk for answer 

Just yestarday i was working with create-react-app and the cross-domain was problem on which i spent few hours and best solution was a plugin to my browser which allow anything. (but blocked my facebook and youtube btw).

I know it's not a proper place, but maybe you know how to deal with this problem in https://github.com/facebookincubator/create-react-app this boilerplate which i said of before? I have a project. which i have finish until weekend end, and maybe you will help me with it :)

**Comment by micooz** [comment]
Sorry for my late, maybe you can show me your project, opensource or not?

**Comment by s3c0nDD** [comment]
hi, project is not open source (which i personally love, i mean i love OS, but it is not examply "mine" project).
boilerplate is [create-react-app](https://github.com/facebookincubator/create-react-app), i work on it and my app isn't very big or so, i have 1 view and 3 components
they (boilerplate) even have some docs [(probably on my issue?)](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#proxying-api-requests-in-development), but i dunno for sure.

i made requests using [axios](https://github.com/mzabriskie/axios) only for this endpoint: [Flickr endpoint doc](https://www.flickr.com/services/feeds/docs/photos_public/)

my code is: 
http://pastebin.com/ty0E1p4M

**I just wanna do** `yarn start` **and my local server on** _localhost:3000_ **should not return me errors when connecting to Flickr Public API.**

**Comment by micooz** [comment]
Hey, you made a mistake at this line:

```
headers: { 'Access-Control-Allow-Origin': '*' }
```

This header **must only** be set on server-side, not in your request.

I want to know the details of your `query` passed to `axios.get`. And, show me your `package.json` pls.

**Comment by s3c0nDD** [comment]
ok, but even without this header was no change.

**query**
>let query = \`https://api.flickr.com/services/feeds/photos_public.gne?format=json&tags=${tag}&nojsoncallback=1`;

**package.json**

[http://pastebin.com/7WEpZVMt](http://pastebin.com/7WEpZVMt)

**Comment by micooz** [comment]
Well, I think I know what your problem is.

Firstly, add:

```
"proxy": "https://api.flickr.com"
```
to your `package.json`.

Then, change your query to:

```
let query = `/services/feeds/photos_public.gne?format=json&tags=${tag}&nojsoncallback=1`;
```

Restart your project and see what happened.

**Comment by s3c0nDD** [comment]
Man, U ARE MY GOD.

Thanks veeeeery much. It works :)

**Comment by micooz** [comment]
You are welcome :smile:.

**Comment by s3c0nDD** [comment]
check your email btw :)
